module.exports = {
  env: {
    browser: true,
    es2021: true,
    commonjs: true,
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2021,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  extends: [
    'prettier',
    'airbnb-base',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
  ],
  plugins: [
    '@typescript-eslint',
    'react',
    'prettier',
    'jsx-a11y',
    'import',
    'unused-imports',
  ],
  rules: {
    'prettier/prettier': [
      'warn',
      {
        singleQuote: false,
        jsxBrackets: false,
        jsxBracketSameLine: false,
        trailingComma: 'all',
        semi: true,
        tabWidth: 4,
        useTabs: true,
        endOfLine: 'auto',
      },
    ],
    'react/display-name': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/quotes': 'off',
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/comma-dangle': 'off',
    '@typescript-eslint/no-unused-expressions': 'off',
    '@typescript-eslint/object-curly-spacing': 'off',
    '@typescript-eslint/semi': ['error', 'always'],
    '@typescript-eslint/no-namespace': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/control-has-associated-label': 'off',
    'import/extensions': 'off',
    'import/no-unresolved': 'warn',
    'import/prefer-default-export': 'warn',
    'import/no-cycle': 'off',
    'import/no-relative-packages': 'off',
    'import/no-extraneous-dependencies': 'off',
    'react/style-prop-object': 'warn',
    'react/jsx-curly-newline': 'off',
    'react/jsx-indent-props': 'off',
    'react/jsx-indent': 'off',
    'react/jsx-wrap-multilines': 'off',
    'react/require-default-props': 'warn',
    'react/function-component-definition': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/destructuring-assignment': 'off',
    'react/prop-types': 'off',
    'react/jsx-filename-extension': [
      1,
      { extensions: ['.tsx', '.jsx'] },
    ],
    'no-console': [
      1,
      { allow: ['error'] },
    ],
    'no-param-reassign': 'warn',
    'operator-linebreak': 'off',
    indent: 'off',
    'no-shadow': 'off',
    'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
    quotes: 'off',
    semi: ['error', 'always'],
    'comma-dangle': 'off',
    'no-unused-expressions': 'off',
    'no-use-before-define': 'off',
    'linebreak-style': 'off',
    eqeqeq: 'warn',
    'wrap-iife': 'off',
    'no-underscore-dangle': 'off',
    'implicit-arrow-linebreak': 'off',
    'function-paren-newline': 'off',
    'nonblock-statement-body-position': 'off',
    curly: 'off',
    'object-curly-newline': 'off',
    'no-async-promise-executor': 'off',
    'max-len': 'off',
    'no-tabs': 'off',
    'no-await-in-loop': 'off',
    'no-plusplus': 'off',
    camelcase: 'warn',
    'no-confusing-arrow': 'off',
    'no-constructor-return': 'off',
    'no-return-assign': 'off',
    'max-classes-per-file': 'off',
    'unused-imports/no-unused-imports': 'warn',
    'unused-imports/no-unused-vars': 'off',
  },
  settings: {
    react: {
      version: 'detect',
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
};